OperatingSystem.create(name: "windows")
OperatingSystem.create(name: "mac")
OperatingSystem.create(name: "linux/ubuntu")

#Windows
OsVersion.create(name: "98", operating_system_id: OperatingSystem.find_by(name: "windows").id)
OsVersion.create(name: "me", operating_system_id: OperatingSystem.find_by(name: "windows").id)
OsVersion.create(name: "2000", operating_system_id: OperatingSystem.find_by(name: "windows").id)
OsVersion.create(name: "xp", operating_system_id: OperatingSystem.find_by(name: "windows").id)
OsVersion.create(name: "vista", operating_system_id: OperatingSystem.find_by(name: "windows").id)
OsVersion.create(name: "7", operating_system_id: OperatingSystem.find_by(name: "windows").id)
OsVersion.create(name: "8", operating_system_id: OperatingSystem.find_by(name: "windows").id)
OsVersion.create(name: "10", operating_system_id: OperatingSystem.find_by(name: "windows").id)
OsVersion.create(name: "other", operating_system_id: OperatingSystem.find_by(name: "windows").id)

#Mac
OsVersion.create(name: "osx 10.5 leopard", operating_system_id: OperatingSystem.find_by(name: "mac").id)
OsVersion.create(name: "osx 10.6 snow leopard", operating_system_id: OperatingSystem.find_by(name: "mac").id)
OsVersion.create(name: "osx 10.7 lion", operating_system_id: OperatingSystem.find_by(name: "mac").id)
OsVersion.create(name: "osx 10.8 mountain lion", operating_system_id: OperatingSystem.find_by(name: "mac").id)
OsVersion.create(name: "osx 10.9 mavericks", operating_system_id: OperatingSystem.find_by(name: "mac").id)
OsVersion.create(name: "osx 10.10 yosemite", operating_system_id: OperatingSystem.find_by(name: "mac").id)
OsVersion.create(name: "osx 10.11 el capitan", operating_system_id: OperatingSystem.find_by(name: "mac").id)
OsVersion.create(name: "osx 10.12 sierra", operating_system_id: OperatingSystem.find_by(name: "mac").id)
OsVersion.create(name: "other", operating_system_id: OperatingSystem.find_by(name: "mac").id)

#Linux/Ubuntu

#ubuntu
OsVersion.create(name: "ubuntu", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "edubuntu", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "ubuntu gnome", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "kubuntu", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "ubuntu kylin", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "lubuntu", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "ubuntu studio", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "xubuntu", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "ubuntu mate", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)

#debian
OsVersion.create(name: "aptosid", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "canaima", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "devuan", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "gnewsense", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "handylinux", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "kali linux", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "kanotix", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "knoppix", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "kurumin", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "mepis", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "mintppc", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "musix gnu+linux", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "nepalinux", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "parsix", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "rxart", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "raspbian", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "sacix", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "siduction", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "skolelinux", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "solydxk", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "sparkylinux", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "steamos", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "sunwahos", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "symphony os", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "salineos", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "tails", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "xanadu", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)
OsVersion.create(name: "other", operating_system_id: OperatingSystem.find_by(name: "linux/ubuntu").id)

GimpVersion.create(name: "GIMP 2.6")
GimpVersion.create(name: "GIMP 2.8")
GimpVersion.create(name: "GIMP 2.9")
